console.log("Testing");
console.log("Checking whether cicd is working");
console.log("patch test");
console.log("minor test");
console.log("MAJOR test");
console.log("commit 1");
console.log("commit 2");
console.log("commit 3");
console.log("commit 3");
console.log("commit 3");
console.log("commit 3");
console.log("commit 3");
console.log("commit 3");
