name: Test
on: 
  push: 
    branches:
      - '**'

jobs:
  base-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm run dev
    