name: Release
on:
    push:
        branches:
            - '**'
jobs:
    release-ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/node@v3
              with:
                  node-version: '20'
            - run: npm install
            - run: echo "Testing release cicd"